### ISSUE TITLE
Errors creating a new feature

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#191]
POSTing a new feature creates this exception:

```
! java.lang.ArrayIndexOutOfBoundsException: -1
! at java.util.ArrayList.elementData(ArrayList.java:422)
! at java.util.ArrayList.get(ArrayList.java:435)
! at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
! at de.ii.xtraplatform.feature.provider.sql.app.SchemaBuilderSql.create(SchemaBuilderSql.java:46)
! at de.ii.xtraplatform.feature.provider.sql.app.SchemaBuilderSql.create(SchemaBuilderSql.java:29)
! at de.ii.xtraplatform.features.domain.ReverseSchemaBuilder.visit(ReverseSchemaBuilder.java:24)
! at de.ii.xtraplatform.features.domain.ReverseSchemaBuilder.visit(ReverseSchemaBuilder.java:17)
! at de.ii.xtraplatform.features.domain.SchemaBase.accept(SchemaBase.java:120)
! at de.ii.xtraplatform.features.domain.SchemaBase.lambda$accept$1(SchemaBase.java:121)
! at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
! at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
! at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
! at de.ii.xtraplatform.features.domain.SchemaBase.accept(SchemaBase.java:122)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.__M_writeFeatures(FeatureProviderSql.java:302)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.writeFeatures(FeatureProviderSql.java)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.__M_createFeatures(FeatureProviderSql.java:237)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.createFeatures(FeatureProviderSql.java)
! at de.ii.ldproxy.wfs3.transactional.CommandHandlerTransactional.postItemsResponse(CommandHandlerTransactional.java:51)
...
```

**Comment by cportele** [comment]
I will try out, if transactions work, if all three conditions are met (no constants, use of an auto-generated id only, no transformations in features-core/geojson) and then close this issue + create new issues for those aspects and also for checking that a collection meets the requirements for enabling transactions.

**Comment by cportele** [comment]
In some cases I still get errors "Cannot build SqlPath, some of required attributes are not set [sortKey]" at `de.ii.xtraplatform.feature.provider.sql.app.PathParserSql.parse(PathParserSql.java:95)`, so I will leave this open for now and we will close this after analyzing this.

**Comment by cportele** [comment]
I also think there is a constraint missing in the list above: In the cases where other tables are joined (nested objects), these are owned and fully controlled by the feature (their id/primary key is not part of the JSON encoding).
