### ISSUE TITLE
Server Error: IO operation was stopped unexpectedly after 0 bytes because of java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

### ISSUE THREAD

**Issue by swiss-knight** [interactive-instruments/ldproxy#587]
Follow up on #583 

I'm facing a new error now, when I click on some of the collection items, (not all of them; many are correctly displayed), e.g. at: http://my-base-server:7080/rest/services/service/collections/{collectionId}/items

Here's the full log which is written and the time I hit the URL:
```
DEBUG [2022-01-26 12:16:17,291] service                 - Processing request: GET /collections/plants/items [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,298] service                 - accept text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,299] service                 - content-type Optional[ApiMediaType{type=text/html, label=HTML, parameter=html, fileExtension=html, qs=1000}] [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,299] service                 - accept-language en-US,en;q=0.5 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,299] service                 - content-language Optional[en] [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,457] service                 - numberMatched 214694 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,457] service                 - numberReturned 10 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,457] service                 - pageSize 10 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,457] service                 - page 1 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,457] service                 - pages 21470 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,487] service                 - accept text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,488] service                 - content-type Optional[ApiMediaType{type=text/html, label=HTML, parameter=html, fileExtension=html, qs=1000}] [91e56014-5062-4898-9fd7-d16f388f98bf] 
ERROR [2022-01-26 12:16:17,489] service                 - Server Error with ID 556cb5ee4ef4fac8: IO operation was stopped unexpectedly after 0 bytes because of java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2 [91e56014-5062-4898-9fd7-d16f388f98bf] 
DEBUG [2022-01-26 12:16:17,491] service                 - Stacktrace: [91e56014-5062-4898-9fd7-d16f388f98bf] 
! java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
! at de.ii.xtraplatform.geometries.domain.ToChars.onCoordinates(ToChars.java:37)
! at de.ii.xtraplatform.geometries.domain.CrsTransform.onCoordinates(CrsTransform.java:32)
! at de.ii.xtraplatform.geometries.domain.ToDoubleArray.onFlush(ToDoubleArray.java:62)
! at de.ii.xtraplatform.geometries.domain.CoordinatesParser.flush(CoordinatesParser.java:91)
! at de.ii.xtraplatform.geometries.domain.CoordinatesParser.close(CoordinatesParser.java:95)
! at de.ii.xtraplatform.geometries.domain.CoordinatesTransformer.close(CoordinatesTransformer.java:134)
! at de.ii.xtraplatform.features.domain.FeatureTokenTransformerValueMappings.onValue(FeatureTokenTransformerValueMappings.java:110)
! at de.ii.xtraplatform.features.domain.FeatureTokenTransformerSchemaMappings.pushValue(FeatureTokenTransformerSchemaMappings.java:254)
! at de.ii.xtraplatform.features.domain.FeatureTokenTransformerSchemaMappings.onValue(FeatureTokenTransformerSchemaMappings.java:196)
! at de.ii.xtraplatform.feature.provider.sql.app.GeometryDecoderWkt.readCoordinates(GeometryDecoderWkt.java:194)
! at de.ii.xtraplatform.feature.provider.sql.app.GeometryDecoderWkt.decode(GeometryDecoderWkt.java:70)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureDecoderSql.handleColumns(FeatureDecoderSql.java:209)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureDecoderSql.handleValueRow(FeatureDecoderSql.java:153)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureDecoderSql.onPush(FeatureDecoderSql.java:105)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureDecoderSql.onPush(FeatureDecoderSql.java:32)
! at de.ii.xtraplatform.streams.app.TransformerFused.onPush(TransformerFused.java:39)
! at de.ii.xtraplatform.streams.app.TransformerFused.onPush(TransformerFused.java:39)
! at de.ii.xtraplatform.streams.app.TransformerFused.onPush(TransformerFused.java:39)
! at de.ii.xtraplatform.streams.app.TransformerFused.onPush(TransformerFused.java:39)
! at de.ii.xtraplatform.streams.app.ReactiveAkka$AsymmetricFlow.lambda$new$c0a97bfb$1(ReactiveAkka.java:315)
! at akka.stream.javadsl.Flow.$anonfun$mapConcat$1(Flow.scala:673)
! at akka.stream.impl.fusing.StatefulMapConcat$$anon$49.onPush(Ops.scala:2237)
! at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
! at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
! at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
! at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
! at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
! at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
! at akka.actor.Actor.aroundReceive(Actor.scala:537)
! at akka.actor.Actor.aroundReceive$(Actor.scala:535)
! at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
! at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
! at akka.actor.ActorCell.invoke(ActorCell.scala:548)
! at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
! at akka.dispatch.Mailbox.run(Mailbox.scala:231)
! at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
! at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
! at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
! at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
! at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
! at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
! Causing: akka.stream.IOOperationIncompleteException: IO operation was stopped unexpectedly after 0 bytes because of java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
! at akka.stream.impl.io.OutputStreamGraphStage$$anon$1.onUpstreamFailure(OutputStreamGraphStage.scala:66)
! at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:525)
! at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
! at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
! at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:61)
! at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:57)
! at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnError.execute(ActorGraphInterpreter.scala:82)
! at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
! at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
! at akka.actor.Actor.aroundReceive(Actor.scala:537)
! at akka.actor.Actor.aroundReceive$(Actor.scala:535)
! at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
! at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
! at akka.actor.ActorCell.invoke(ActorCell.scala:548)
! at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
! at akka.dispatch.Mailbox.run(Mailbox.scala:231)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
! at java.base/java.lang.Thread.run(Unknown Source)
DEBUG [2022-01-26 12:16:17,491] service                 - Sending response: 500 Internal Server Error [91e56014-5062-4898-9fd7-d16f388f98bf] 
```

It seems all table without geometries are rendered fine.    
Some tables with a single geometry column are not fine (geometry type `Point` _or_ another one with a generic `Geometry` geometry column), but some other are working fine.    
Some tables with multiple geometry column**s** are not fine (e.g. `POINT`
`MULTIPOLYGON`, but one is (it has 3 columns with a geometry type `MultiPolygon`).

**Comment by cportele** [comment]
@swiss-knight - From the stacktrace it looks like an issue with the WKT. Maybe the data has some variant that is currently not supported? Could you show the WKT of first 'plants' feature?

**Comment by swiss-knight** [comment]
Yes, the first feature has a `location` value as follow:
```
"POINT Z (7.802601915141556 45.80764638943693 5.137517447553)"
```

a `ground_geom` value as follow:
```
"MULTIPOLYGON(((7.71535618748107 45.79933923597178,7.716346052547292 45.799461274155846,7.715990315192895 45.79926797932015,7.71535618748107 45.79933923597178)),((8.885499800059725 46.307615382338895,8.884752137689304 46.307328030177814,8.885258955305865 46.307834392646164,8.88551684794402 46.30776811628789,8.885499800059725 46.307615382338895)),((7.710860051893582 45.799163885406074,7.710570606931344 45.79950054746023,7.710665927456153 46.30062396035717,7.712503106938487 45.79943940819318,7.712055086972375 45.79919331988077,7.71106499286079 45.79906224980087,7.710860051893582 45.799163885406074)),((7.71902089060152 45.79996615164728,7.722062646332783 46.30202268149989,7.723271995621324 46.30257365094084,7.724506043570904 46.302602442919046,7.726281616668257 46.30202128878034,7.72600073566041 46.30171907370672,7.723255950815786 46.301035331803156,7.72179714717924 46.300379665196026,7.719706681485078 45.799885201163335,7.71902089060152 45.79996615164728)),((8.897348098534565 46.33162078289779,8.896623791508954 46.330766379841606,8.89675396647603 46.329325152527424,8.896345400489878 46.3286196343698,8.896374171691294 46.327755533349546,8.89600722462339 46.32714844752849,8.892318079277175 46.32469465092751,8.889857966466296 46.32253989355803,8.889399517781175 46.32239281663361,8.888703775454202 46.32259966708162,8.888271773000755 46.32247024127397,8.888279476980692 46.32227220476232,8.889316362512089 46.32171009653413,8.889387547513024 46.320971415813574,8.889162060361228 46.32079436129762,8.888144437396123 46.32110430078552,8.887571569376387 46.32104865321159,8.8875978053872 46.32057146720684,8.888442130593399 46.319606957937566,8.888060158470044 46.319404913569095,8.886809651821356 46.31925896663643,8.886738393246118 46.320483493556246,8.887479192156542 46.32537747631509,8.888536774508768 46.330456341404116,8.88905204579074 46.33029679083346,8.889667326598016 46.33047784926589,8.893845597827811 46.333240353375174,8.896078044622584 46.33414735277575,8.897069810920113 46.33528622608743,8.898049781157914 46.33598438054484,8.899312067368705 46.336552925244675,7.700554376567403 46.336860795172186,7.701242597742305 46.336851909291575,7.701506813522493 46.3365335945806,7.70081325826902 46.334896062576924,8.899721580172839 46.333425613743564,8.897937754702681 46.332296972890525,8.897348098534565 46.33162078289779)),((8.89853643499602 46.31397096083502,8.898967842454008 46.313596511465086,8.89875702559286 46.31348226721462,8.896479588180908 46.31377253738368,8.896765965445068 46.31476753756365,8.896533289692002 46.31480652299392,8.896215497668532 46.314576688099635,8.89576288557833 46.314645495060965,8.895315575146512 46.314912170166615,8.895029564827482 46.31538370385089,8.895252021383376 46.31690136698131,8.897215215232528 46.321347696903224,8.898267878547273 46.32282766582989,7.700362731429583 46.323943285341976,7.70129472506651 46.3247949813306,7.702534714502028 46.327918981981455,7.704884060533222 46.332198250192,7.708307685272588 46.3348800280782,7.709914570405494 46.336658608433176,7.712044518200782 46.33760261875577,7.712601130990451 46.338009248617226,7.713342283419418 46.33803568938459,7.715650829157403 46.33694383220367,7.718969902487989 46.33480413927978,7.72123455910864 46.33306503675311,7.72164144022442 46.33226795117658,7.720438283286911 46.33101508926559,7.719507829242342 46.32928179539896,7.717404311659906 46.32739287283306,7.71485900233368 46.32262156179539,7.711949711705445 46.319735357417095,7.709619019998031 46.319504743653916,7.708586212752155 46.31924824122531,7.703188834424412 46.316529055192994,7.70276397430098 46.31714636065412,7.702200093935246 46.317423567852245,7.7010842411849 46.31745598199157,7.700452218780833 46.31713124802039,7.700350470003248 46.31672768770471,7.700822763714572 46.31642468108146,7.702306308079456 46.316063616654176,7.703002746551255 46.31636951263699,7.702822371560342 46.31593997970143,7.701832626724213 46.315349963436645,7.701590268979332 46.315029196259566,7.70273826597324 46.313781737910105,7.702787175121723 46.313187289732944,7.70206971189477 46.31209890798542,7.701537707516606 46.31162893253444,8.89963088749639 46.31121269569089,8.897738466692768 46.310364376138935,8.897406509802643 46.31008974148879,8.89801983927488 46.30972194807233,8.89895238185453 46.30963794389751,7.700367152414136 46.31010553233822,7.700834877122515 46.31011748599781,7.701371036803344 46.30977766252608,7.701226970862767 46.30924868912351,8.899228519590446 46.307834941605805,8.89418945294144 46.306316346409055,8.888146566131804 46.305116294136816,8.886221067094647 46.30496099277113,8.884990814704434 46.30507568892942,8.884438033252671 46.30528068885835,8.884520684279906 46.30545957640741,8.886230407207453 46.30531176292407,8.886728834630118 46.30550332505907,8.886881375202204 46.306356104647115,8.887187539490908 46.306640096425255,8.887106997232431 46.30702800550493,8.887795322249215 46.30703718953495,8.88969351672851 46.30665298453161,8.88900613562897 46.307165636199976,8.887550380623653 46.30758915270682,8.884998500177788 46.30926827058106,8.884919613445986 46.30971913688644,8.885205812114357 46.31022831844514,8.88623455045332 46.309855280678775,8.887187522130239 46.310050024816185,8.88647914694616 46.310751869534236,8.88552635332001 46.31105196130828,8.885285254074988 46.31126197757309,8.88526402882661 46.3119280392742,8.8855422904189 46.31262626216976,8.88606118649807 46.31309647876236,8.887499258543391 46.31346496100852,8.888352324056873 46.31331908217189,8.890020474427683 46.31257793304814,8.891416013925692 46.31232610545008,8.892730308521152 46.312435191480155,8.893380264570478 46.31294867768996,8.894873674554542 46.31344231632024,8.898644425112254 46.31267397173011,8.898470441242246 46.31296412581061,7.700073218975855 46.31317737280571,7.701155941628183 46.31384717733814,7.701385069617987 46.31415911907808,7.700282101817975 46.31466821134049,8.897521035828403 46.31532463291876,8.89739842108392 46.315110280272876,8.897532270388174 46.31477565923747,8.89853643499602 46.31397096083502)))"
```

+ two other multipolygon geometries `patch_geom` and `user_geom` similar than the previous one but much more complex.

All geometries are well displayed, e.g. in QGIS or when loaded in Python (Shapely).

And of course, there are some attributes encoded as text, int, float, array or json.

**Comment by azahnen** [comment]
Are you still interested in fixing this?

**Comment by swiss-knight** [comment]
@[azahnen](https://github.com/azahnen) Yes I am.

**Comment by swiss-knight** [comment]
Setting the `forceAxisOrder` to `LON_LAT` instead of `NONE` in the provider yaml file also fixed the current issue:

```
nativeCrs:
  code: 4326
  forceAxisOrder: LON_LAT
```

As per the doc: https://github.com/interactive-instruments/ldproxy/tree/master/docs/de/configuration/providers
(search for `forceAxisOrder` within the `nativeCrs` row)

See related: https://github.com/interactive-instruments/ldproxy/issues/589
